### ISSUE TITLE
stderr output: 'No source or binary directory provided'

### ISSUE THREAD

**Issue by kurcha01-arm** [autowarefoundation/tvm_vendor#1]
```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
```

The package builds successfully but emits an error. From a quick glance I think this might be due to [these lines](https://github.com/autowarefoundation/tvm_vendor/blob/main/CMakeLists.txt#L80)

**Comment by kurcha01-arm** [comment]
I believe this happens when the package is build using CMake 3.13 or later:
https://gitlab.kitware.com/cmake/cmake/-/issues/18817

**Comment by JWhitleyWork** [comment]
Thanks for the notification. This should be an easy fix.
