### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Autostone-c** [autowarefoundation/tvm_vendor#15]
ubuntu20.04 ros2(humble)

git clone -b 0.7.0 --single-branch https://github.com/autowarefoundation/tvm_vendor.git

colcon build --symlink-install --packages-select tvm_vendor

Starting >>> tvm_vendor
--- stderr: tvm_vendor
error: patch failed: cmake/config.cmake:115
error: cmake/config.cmake: patch does not apply
make[2]: *** [CMakeFiles/tvm-build.dir/build.make:126: tvm-build-prefix/src/tvm-build-stamp/tvm-build-patch] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/tvm-build.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< tvm_vendor [0.73s, exited with code 2]

**Comment by jieunko** [comment]
Hi I am having same problem?
Could you share me how you solved the problem?
